export default [
    // 'all',
    // 'backdrop-filter',
    // 'block-size',
    'bottom',
    // 'caret-color',
    'clear',
    'color',
    'columns',
    'cursor',
    'display',
    'filter',
    'float',
    'gap',
    'height',
    'inline-size',
    'left',
    'letterSpacing',
    'opacity',
    'order',
    'position',
    'resize',
    'right',
    'rotate',
    'rowGap',
    'top',
    'userSelect',
    'verticalAlign',
    'visibility',
    'whiteSpace',
    'widows',
    'width',
    'willChange',
    'wordBreak',
    'wordSpacing',
    'writingMode',
    'zIndex',
]